### ISSUE TITLE
Flexbox-based layout is broken if loaded into ng-view

### ISSUE THREAD

**Issue by MikeMitterer** [angular/angular.dart#1297]
Consider the following page-layout: (very similar like this: http://www.cssplay.co.uk/layouts/cssplay-flex-basic-layout.html)

``` html
html
head
body
   header
   section (middle)
      nav (sidenav)
      main
          <ng-view></ng-view> 
   footer
```

If I load my view into ng-view the sticky header + footer is not "sticky" anymore - they scroll with the whole page. It's definitive a Angular-Problem because if I take the content from my view and replace <ng-view></ng-view> with it, everything is fine.

**Comment by newmanw** [comment]
I am having a similar problem.  However I do not understand this solution:


```html
html
head
body
   header
   section (middle)
      nav (sidenav)
      main
         div
            h1
   footer
```

Where is the ng-view in that solution?  Need that for the router
