### ISSUE TITLE
ng-if does not work for dynamically created elements.

### ISSUE THREAD

**Issue by MikeMitterer** [angular/angular.dart#1562]
This

``` dart
<span ng-if="params[0]">, Title: {{params[0]}}</span>
```

shows nothing. But this:

``` dart
<span>, Title II: {{params[0]}}</span>
```

works

JS-Sample: http://www.mikemitterer.at/fileadmin/sourcesamples/accordion/
index.html: https://github.com/MikeMitterer/Angular.Accordion/blob/master/web/index.html
MyBindHtmlComponent that creates the component: http://goo.gl/BlihdM

There is a second bug: In the above sample params must be available in the AppController (wrong) and and the according component (right)
AppController: http://goo.gl/2YDJRd
Component: http://goo.gl/BlihdM

**Comment by Hir06** [comment]
I am still facing issue. Had anyone able to resolve this bug?
