### ISSUE TITLE
Dependency version of html5lib is incompatible with Polymer

### ISSUE THREAD

**Issue by stevenroose** [angular/angular.dart#1594]
Look here
https://github.com/dart-lang/polymer-dart/blob/master/pubspec.yaml
and here
https://github.com/angular/angular.dart/blob/master/pubspec.yaml

When depending on both Angular and Polymer, makes pub get two random old versions that happen to have matching browser dependency.
There should be a way to resolve this dependency issues. What's wrong with using `html5lib: any`?
Or alternatively monitor all dependencies for new versions and test the library against the new version and then update.

**Comment by rkirov** [comment]
should be good now
