### ISSUE TITLE
need better support for mocking components

### ISSUE THREAD

**Issue by trinarytree** [angular/angular.dart#1600]
when a component A uses a component B and B is complex or we simply want to abstract away what it does, a test for A may want to mock B.  this is problematic in Angular right now because if we do this
```dart
@Component(selector: 'b', ...)
class B {...}

@Component(selector: 'b', ...)
class MockB {...}
```

then it is not clear which component(s) will get bound to the selector 'b'.  if we didn't care about testing, reasonable answers might be "both", "neither, it's an error", "first one wins (although the order isn't clear)", "last one wins", "non-deterministic, so don't do it".

but if we want to test with the ability to abstract out a component dependency, the above aren't good policies.  we'd need a mechanism that would make it clear that the mock should win.  e.g.
```dart
@Component(selector: 'b', override: true, ...)
```

notice that we cannot simply use dependency injection to rebind the controller (i.e. rebind B to MockB) because we need to rebind the (controller, template) combination.  besides, conceptually, we want to rebind the selector, and the name of the original controller class shouldn't be important.

can we get a mechanism like the above to improve testability?

**Comment by naomiblack** [comment]
We will not be addressing this in 1.x but have added it to the 2.0 roadmap. See https://github.com/angular/angular/issues/450
