### ISSUE TITLE
Issue with ViewPort and Transcluding Components

### ISSUE THREAD

**Issue by vsavkin** [angular/angular.dart#1630]
Currently, ViewPort has the following two responsibilities:

1. Managing a list of views.
2. Modifying the DOM. So it acts as a placeholder.

The second one is problematic when we emulate shadow DOM. The shadow DOM emulation uses the View tree to get the list of nodes to redistribute among insertion points. If this redistribution happens first, and the ViewPort's modification second, then the redistribution gets invalidated, and some DOM nodes will not be displayed. 

I think we have to rethink how ViewPort and Transcluding Components work together. Maybe we should have a ViewPort that does not modify the DOM?

**Comment by naomiblack** [comment]
This is addressed in Angular 2.
