### ISSUE TITLE
Failed to watch path, path  (OS Error: No space left on device, errno = 28)

### ISSUE THREAD

**Issue by thaniyarasu** [angular/angular.dart#1634]
dev@dev:~/dart/demo$ dart --version
Dart VM version: 1.8.3 (Mon Dec  1 08:42:49 2014) on "linux_x64"
dev@dev:~/dart/demo$ pub --version
Pub 1.8.3
dev@dev:~/dart/demo$ 
----------pubspec.yaml--------------
name: demo
description: A sample web application
dependencies:
  browser: any
-------------------------------
dev@dev:~/dart/demo$ pub serve
Loading source assets... 
Serving demo web on http://localhost:8080
Build completed successfully
then all are working fine 

but when i add angular into pubspec.yaml 
----------pubspec.yaml--------------
name: demo
description: A sample web application
dependencies:
  browser: any
  angular: any
-------------------------------

dev@dev:~/dart/demo$ pub serve
Your pubspec has changed, so we need to update your lockfile:
Resolving dependencies... (24.3s)
+ analyzer 0.15.7 (0.22.4 available)
+ angular 1.0.0
+ args 0.10.0+2 (0.12.2+1 available)
+ barback 0.14.2 (0.15.2+2 available)
+ code_transformers 0.1.6 (0.2.3+2 available)
+ collection 0.9.4 (1.1.0 available)
+ di 3.3.2 (3.3.3 available)
+ html5lib 0.10.0 (0.12.0 available)
+ intl 0.11.12
+ logging 0.9.2
+ observe 0.10.1+2 (0.12.2 available)
+ path 1.3.1
+ perf_api 0.0.9
+ petitparser 1.3.2
+ pool 1.0.1
+ route_hierarchical 0.5.0 (0.6.1 available)
+ smoke 0.1.0+1 (0.2.1+1 available)
+ source_maps 0.9.4 (0.10.0+1 available)
+ source_span 1.0.2
+ stack_trace 1.1.1
+ utf 0.9.0+1
Changed 21 dependencies!
Precompiling dependencies... 
Loading source assets... 
Loading di/module_transformer and smoke/src/default_transformer transformers... (2.2s)
Precompiled di and smoke.
Precompiling executables... 
Loading source assets... 
Loading di/module_transformer and smoke/src/default_transformer transformers... 
Precompiled angular:pub_build.
Precompiled angular:parser_generator_for_spec.
Precompiled angular:template_cache_generator.
Precompiled angular:expression_extractor.
Loading source assets... 
Bad state: Cannot add new events after calling close
dart:async                                            _BroadcastStreamController.addError
package:watcher/src/directory_watcher/linux.dart 136  _LinuxDirectoryWatcher._watchSubdir.<fn>
dart:isolate                                          _RawReceivePortImpl._handleMessage
This is an unexpected error. Please run

    pub --trace 'serve'

and include the results in a bug report on http://dartbug.com/new.
dev@dev:~/dart/demo$ pub --trace 'serve'
Loading source assets... 
Failed to watch path, path = '/home/dev/dart/demo/web/packages/source_span/src' (OS Error: No space left on device, errno = 28)
---- Log transcript ----
FINE: Pub 1.8.3
FINE: Clean up system cache temp directory /home/dev/.pub-cache/_temp.
FINE: Loading asset environment...
FINE: Loading package graph...
FINE: Loading package graph finished (0.1s).
FINE: Initializing barback...
FINE: Serving packages on localhost:0.
FINE: Providing sources for demo|lib.
FINE: Loading source assets finished (0.0s).
FINE: Provided sources.
FINE: Loading transformers...
FINE: Transformer dependencies:
FINE: Loading transformers finished (0.0s).
FINE: Initializing barback finished (0.0s).
FINE: Loading asset environment finished (0.2s).
FINE: Bound admin server to localhost:8079.
FINE: Providing sources for demo|web.
ERR : Failed to watch path, path = '/home/dev/dart/demo/web/packages/source_span/src' (OS Error: No space left on device, errno = 28)
FINE: Exception type: FileSystemException
FINE: dart:async                                            _BoundSinkStream.listen
    | package:watcher/src/directory_watcher/linux.dart 283  _LinuxDirectoryWatcher._listen
    | package:watcher/src/directory_watcher/linux.dart 63   _LinuxDirectoryWatcher._LinuxDirectoryWatcher
    | package:watcher/src/directory_watcher/linux.dart 127  _LinuxDirectoryWatcher._watchSubdir
    | package:watcher/src/directory_watcher/linux.dart 70   _LinuxDirectoryWatcher._LinuxDirectoryWatcher.<fn>
    | dart:isolate                                          _RawReceivePortImpl._handleMessage
    | ===== asynchronous gap ===========================
    | dart:async                                            _StreamImpl.listen
    | package:watcher/src/directory_watcher/linux.dart 283  _LinuxDirectoryWatcher._listen
    | package:watcher/src/directory_watcher/linux.dart 67   _LinuxDirectoryWatcher._LinuxDirectoryWatcher
    | package:watcher/src/directory_watcher/linux.dart 127  _LinuxDirectoryWatcher._watchSubdir
    | package:watcher/src/directory_watcher/linux.dart 70   _LinuxDirectoryWatcher._LinuxDirectoryWatcher.<fn>
    | dart:isolate                                          _RawReceivePortImpl._handleMessage
    | ===== asynchronous gap ===========================
    | dart:async                                            _StreamImpl.listen
    | package:watcher/src/directory_watcher/linux.dart 283  _LinuxDirectoryWatcher._listen
    | package:watcher/src/directory_watcher/linux.dart 67   _LinuxDirectoryWatcher._LinuxDirectoryWatcher
    | package:watcher/src/directory_watcher/linux.dart 127  _LinuxDirectoryWatcher._watchSubdir
    | package:watcher/src/directory_watcher/linux.dart 70   _LinuxDirectoryWatcher._LinuxDirectoryWatcher.<fn>
    | dart:isolate                                          _RawReceivePortImpl._handleMessage
    | ===== asynchronous gap ===========================
    | dart:async                                                                                                                              _StreamImpl.listen
    | package:watcher/src/directory_watcher/linux.dart 283                                                                                    _LinuxDirectoryWatcher._listen
    | package:watcher/src/directory_watcher/linux.dart 67                                                                                     _LinuxDirectoryWatcher._LinuxDirectoryWatcher
    | package:watcher/src/directory_watcher/linux.dart 28                                                                                     LinuxDirectoryWatcher.LinuxDirectoryWatcher.<fn>
    | package:watcher/src/directory_watcher/resubscribable.dart 49                                                                            ResubscribableDirectoryWatcher.ResubscribableDirectoryWatcher.<fn>
    | dart:async                                                                                                                              _StreamImpl.listen
    | /mnt/data/b/build/slave/dart-editor-linux-stable/build/dart/sdk/lib/_internal/pub_generated/lib/src/barback/asset_environment.dart 784  AssetEnvironment._watchDirectorySources
    | /mnt/data/b/build/slave/dart-editor-linux-stable/build/dart/sdk/lib/_internal/pub_generated/lib/src/barback/asset_environment.dart 716  AssetEnvironment._provideDirectorySources
    | /mnt/data/b/build/slave/dart-editor-linux-stable/build/dart/sdk/lib/_internal/pub_generated/lib/src/barback/asset_environment.dart 257  AssetEnvironment.serveDirectory
    | /mnt/data/b/build/slave/dart-editor-linux-stable/build/dart/sdk/lib/_internal/pub_generated/lib/src/command/serve.dart 209              ServeCommand._startServer.<fn>
    | dart:isolate                                                                                                                            _RawReceivePortImpl._handleMessage
    | ===== asynchronous gap ===========================
    | dart:async                                                                                                                  scheduleMicrotask
    | /mnt/data/b/build/slave/dart-editor-linux-stable/build/dart/sdk/lib/_internal/pub_generated/lib/src/command/serve.dart 207  ServeCommand._startServer
    | /mnt/data/b/build/slave/dart-editor-linux-stable/build/dart/sdk/lib/_internal/pub_generated/lib/src/command/serve.dart 148  ServeCommand.onRunTransformerCommand.<fn>.join0.join1.<fn>.<fn>.join2.continue0
    | /mnt/data/b/build/slave/dart-editor-linux-stable/build/dart/sdk/lib/_internal/pub_generated/lib/src/command/serve.dart 168  ServeCommand.onRunTransformerCommand.<fn>.join0.join1.<fn>.<fn>.join2
    | /mnt/data/b/build/slave/dart-editor-linux-stable/build/dart/sdk/lib/_internal/pub_generated/lib/src/command/serve.dart 175  ServeCommand.onRunTransformerCommand.<fn>.join0.join1.<fn>.<fn>
    | dart:isolate                                                                                                                _RawReceivePortImpl._handleMessage
    | ===== asynchronous gap ===========================
    | dart:async                                                                                                                  _Future.then
    | /mnt/data/b/build/slave/dart-editor-linux-stable/build/dart/sdk/lib/_internal/pub_generated/lib/src/command/serve.dart 111  ServeCommand.onRunTransformerCommand.<fn>.join0.join1.<fn>
    | dart:isolate                                                                                                                _RawReceivePortImpl._handleMessage
    | ===== asynchronous gap ===========================
    | dart:async                                                                                                                  _Future.then
    | /mnt/data/b/build/slave/dart-editor-linux-stable/build/dart/sdk/lib/_internal/pub_generated/lib/src/command/serve.dart 105  ServeCommand.onRunTransformerCommand.<fn>.join0.join1
    | /mnt/data/b/build/slave/dart-editor-linux-stable/build/dart/sdk/lib/_internal/pub_generated/lib/src/command/serve.dart 189  ServeCommand.onRunTransformerCommand.<fn>.join0
    | /mnt/data/b/build/slave/dart-editor-linux-stable/build/dart/sdk/lib/_internal/pub_generated/lib/src/command/serve.dart 193  ServeCommand.onRunTransformerCommand.<fn>
    | dart:isolate                                                                                                                _RawReceivePortImpl._handleMessage
    | ===== asynchronous gap ===========================
    | dart:async                                                                                                                   scheduleMicrotask
    | /mnt/data/b/build/slave/dart-editor-linux-stable/build/dart/sdk/lib/_internal/pub_generated/lib/src/command/serve.dart 92    ServeCommand.onRunTransformerCommand
    | /mnt/data/b/build/slave/dart-editor-linux-stable/build/dart/sdk/lib/_internal/pub_generated/lib/src/command/barback.dart 63  onRun
    | dart:async                                                                                                                   Future.Future.sync
    | /mnt/data/b/build/slave/dart-editor-linux-stable/build/dart/sdk/lib/_internal/pub_generated/lib/src/command.dart 206         PubCommand.run
    | /mnt/data/b/build/slave/dart-editor-linux-stable/build/dart/sdk/lib/_internal/pub_generated/bin/pub.dart 164                 invokeCommand.<fn>.break0.join0
    | /mnt/data/b/build/slave/dart-editor-linux-stable/build/dart/sdk/lib/_internal/pub_generated/bin/pub.dart 177                 invokeCommand.<fn>.break0
    | /mnt/data/b/build/slave/dart-editor-linux-stable/build/dart/sdk/lib/_internal/pub_generated/bin/pub.dart 235                 invokeCommand.<fn>.continue0
    | /mnt/data/b/build/slave/dart-editor-linux-stable/build/dart/sdk/lib/_internal/pub_generated/bin/pub.dart 239                 invokeCommand.<fn>
    | dart:isolate                                                                                                                 _RawReceivePortImpl._handleMessage
    | ===== asynchronous gap ===========================
    | dart:async                                                                                                          scheduleMicrotask
    | /mnt/data/b/build/slave/dart-editor-linux-stable/build/dart/sdk/lib/_internal/pub_generated/bin/pub.dart 145        invokeCommand
    | /mnt/data/b/build/slave/dart-editor-linux-stable/build/dart/sdk/lib/_internal/pub_generated/bin/pub.dart 98         runPub.<fn>
    | dart:async                                                                                                          Future.Future.sync
    | /mnt/data/b/build/slave/dart-editor-linux-stable/build/dart/sdk/lib/_internal/pub_generated/lib/src/utils.dart 98   captureErrors.<fn>
    | package:stack_trace/src/chain.dart 78                                                                               Chain.capture
    | /mnt/data/b/build/slave/dart-editor-linux-stable/build/dart/sdk/lib/_internal/pub_generated/lib/src/utils.dart 112  captureErrors
    | /mnt/data/b/build/slave/dart-editor-linux-stable/build/dart/sdk/lib/_internal/pub_generated/bin/pub.dart 97         runPub
    | /mnt/data/b/build/slave/dart-editor-linux-stable/build/dart/sdk/lib/_internal/pub_generated/bin/pub.dart 84         main.<fn>
    | dart:isolate                                                                                                        _RawReceivePortImpl._handleMessage
---- End log transcript ----
Unhandled exception:
Uncaught Error: Bad state: Future already completed
Stack Trace:
#0      completeError (dart:async/future_impl.dart:21)
#1      _rootRunBinary (dart:async/zone.dart:914)
#2      _ZoneDelegate.runBinary (dart:async/zone.dart:515)
#3      handleUncaughtError (package:stack_trace/src/stack_zone_specification.dart:161)
#4      _CustomZone.handleUncaughtError (dart:async/zone.dart:779)
#5      _CustomZone.runBinaryGuarded (dart:async/zone.dart:722)
#6      _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:358)
#7      _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:374)
#8      _DelayedError.perform (dart:async/stream_impl.dart:606)
#9      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:711)
#10     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:671)
#11     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:210)
#12     registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:124)
#13     _rootRun (dart:async/zone.dart:891)
#14     _CustomZone.run (dart:async/zone.dart:796)
#15     _CustomZone.runGuarded (dart:async/zone.dart:704)
#16     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:729)
#17     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:210)
#18     registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:124)
#19     _rootRun (dart:async/zone.dart:895)
#20     _CustomZone.run (dart:async/zone.dart:796)
#21     _CustomZone.runGuarded (dart:async/zone.dart:704)
#22     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:729)
#23     _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
#24     _asyncRunCallback (dart:async/schedule_microtask.dart:48)
#25     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:84)
#26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:131)

#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:886)
#1      _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
#2      _asyncRunCallback (dart:async/schedule_microtask.dart:48)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:84)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:131)
dev@dev:~/dart/demo$ 

any solution ?

**Comment by rkirov** [comment]
I can't reproduce this but it might has something to do with your machine `Failed to watch path, path = '/home/dev/dart/demo/web/packages/source_span/src' (OS Error: No space left on device, errno = 28)`
