### ISSUE TITLE
ng-click and ng-disabled directive on a button tag does trigger the click function anyway

### ISSUE THREAD

**Issue by Kaishiyoku** [angular/angular.dart#1636]
Hello,

When using the following markup, the click function is called under Javascript at the Internet Explorer 11 anyway:

Dart:
```dart
bool isDisabled = true;

void clickFunction() {
  print("button clicked");
}
```

Html:
```html
<button ng-click="clickFunction()" ng-disabled="isDisabled">
  Click Me!
</button>
```

Sincere regards,
Kaishiyoku.

**Comment by naomiblack** [comment]
Vic, can you try to reproduce this on IE and investigate?

**Comment by vicb** [comment]
@Kaishiyoku could you please share your project files in a gist. What Dart and Angular version do you use, do is work with other browsers ?

**Comment by Kaishiyoku** [comment]
@vicb I used Angular.Dart 1.0.0 when I experienced the bug. Currently I'm using Angular.Dart 1.1.0. The problem occurs in all commonly used browsers like IE, Firefox, Chrome and also under Dart in the Dartium browser.

I have come across the original cause of the problem - the css declaration at the buttons when they are disabled: `pointer-events`. If this CSS attribute isn't being set the anchor still fires the onclick function. Here is an example project: https://github.com/Kaishiyoku/angular.dart.ng-click-disabled-bug-example (please take a look at the CSS file because I had to change the `pointer-events` attribute for anchors, with the use of Bootstrap they are already being set.

**Comment by vicb** [comment]
@Kaishiyoku there is no `disabled` attribute on `<a>` - there is one on `<button>` though.

It explains why `ng-disabled` has not effect in your use case.
