### ISSUE TITLE
@Deprecated is used even though no future version is planned

### ISSUE THREAD

**Issue by matanlurey** [angular/angular.dart#1642]
Most projects I work on rely on Dart analyzer, and it's unfortunate when there are deprecation warnings for things that will never be fixed or replaced. Might I suggest removing the annotation in these cases (I talked to Rado about ```BoundViewFactory```, for example: https://github.com/angular/angular.dart/blob/master/lib/core_dom/view_factory.dart#L12)

(Bonus: As Angular 2 comes together, maybe start highlighting things in Angular Dart that won't exist in Angular 2 with ```@Deprecated```, but not before then)

**Comment by bwnyasse** [comment]
+1 ! Mark as @Deprecated things that won't exist in Angular 2 would prepare developers for an easy migration.

**Comment by bgourlie** [comment]
I disagree with using `@Deprecated` this way.  `@Deprecated` should only be used if the new alternative already exists in the library that the user is currently depending on.  Migration guides are a better approach to figuring out what needs to be changed when moving from one major version to another.

I do think that any deprecation warnings that currently exist (as in view_factory.dart linked by @matanlurey) should document the preferred alternative.   If there is none, the deprecation warning should be removed altogether.

**Comment by naomiblack** [comment]
This is really only an issue for BoundViewFactory. Assigning to Rado to make the fix (remove @deprecated since we will not be replacing BoundViewFactory in 1.x)
