### ISSUE TITLE
Fix wrong string optimization/comment in change_detection/dirty_checking_change_detector.dart

### ISSUE THREAD

**Issue by BlackHC** [angular/angular.dart#1656]
Introduced in: https://github.com/angular/angular.dart/commit/f01e2867543cb439dd1ad1db41d9c616f418baab

```
bool _looseIdentical(dst, src) {
  if (identical(dst, src)) return true;

  if (dst is String && src is String && dst == src) {
    // this is false change in strings we need to recover, and pretend it is the same. We save the
    // value so that next time identity can pass
    dst = src;
    return true;
  }
```

Assigning src to dst doesn't change anything because it's a local variable. 

Thanks,
 Andreas

PS: @vicb has asked me to add an issue for this.

**Comment by rkirov** [comment]
Sounds like a trivial PR, are you or @vicb making one or should I do it?

**Comment by BlackHC** [comment]
Thanks @vicb !
