### ISSUE TITLE
angular.dart build is broken by Dart SDK 1.13

### ISSUE THREAD

**Issue by kmillikin** [angular/angular.dart#1743]
The next version of the Dart SDK will be 1.13.  It removes the deprecated package dart:profiler which seems to be used by angular.dart and packages it depends on (for example, and older version of the Dart Analyzer).

I tried to build Angular 2 which in turn builds Angular 1.1.2 for a benchmark baseline, and that build fails.  See https://github.com/angular/angular/issues/4677

**Comment by a14n** [comment]
Could someone work on this issue because **it breaks several existing apps** that worked for a long time :-(
In my cases it's the *intl* dependency that leads to error. See dart-lang/sdk#25009

The only workaround I have is to stay stuck with SDK 1.12.2.

**Comment by rkirov** [comment]
This should be fixed by https://github.com/angular/angular.dart/commit/66bc437bcb2a7862c1c291497887851dc391f81b
and landed in 1.1.2+2

**Comment by a14n** [comment]
Thanks for the info.
