### ISSUE TITLE
ngChange is not called immediately

### ISSUE THREAD

**Issue by seongjaelee** [angular/angular.dart#1745]
When I make a small test project with the following code,
```html
<input
    type="text"
    ng-change="ctrl.ngChange()"
    ng-keyUp="ctrl.ngKeyUp()"
    ng-model="ctrl.text"/>
```
```dart
void ngChange() {
  print('ngChange');
  print(text);
}
void ngKeyUp() {
  print('ngKeyUp');
  print(text);
}
```
When I just type a character, only ngKeyUp is called.
ngChange is only called whenever enter is pressed, or the user leaves the form element.

However, ngChange spec in AngularJs says:
"The expression is evaluated immediately, unlike the JavaScript onchange event which only triggers at the end of a change (usually, when the user leaves the form element or presses the return key)."
https://docs.angularjs.org/api/ng/directive/ngChange

**Comment by zoechi** [comment]
Have you tried if `ng-input` does wha you want? I find the JS way confusing because the behavior differs from the input events behavior. If ng-input does what you want, I'd see this as an improvement.

**Comment by seongjaelee** [comment]
Thanks Günter!

ng-input does what I want. However, this is a question about the spec. I thought AngularJs and AngularDart works shares the same ng directive spec. If it is not, don't we need some kind of documentation?

**Comment by zoechi** [comment]
Angular.dart was a complete rewrite and an attempt to fix mistakes in Angular.js. I assume this change was to get rid of confusing discrepancies with DOM events.

**Comment by seongjaelee** [comment]
I see. Closing the issue. Thanks you very much! :)
