### ISSUE TITLE
Access the host component from a directive issue

### ISSUE THREAD

**Issue by vladimiravramov** [angular/angular.dart#1762]
I've stuck with the same problem which describe [here](https://github.com/angular/angular/issues/8277#issuecomment-216206046).
How to access to the host component from a directive?
Is it possible? Which way is correct??

**Comment by zoechi** [comment]
I suspect you meant to post it in https://github.com/dart-lang/angular2

**Comment by vladimiravramov** [comment]
Yes, I've missed angular version. Thx.
