### ISSUE TITLE
Port RouterLinkActive from TypeScript

### ISSUE THREAD

**Issue by franklinyu** [angular/angular.dart#1766]
Feature request. See [documentation](https://angular.io/docs/ts/latest/api/router/index/RouterLinkActive-directive.html) and [source](https://github.com/angular/angular/blob/2.3.0/modules/%40angular/router/src/directives/router_link_active.ts). For usage, refer to [this answer on StackOverflow](http://stackoverflow.com/questions/34323480/in-angular-2-how-do-you-determine-the-active-route/#37947435).

**Comment by zoechi** [comment]
The relevant repo is https://github.com/dart-lang/angular2 
Here is for Angular.dart 1.x
PR are welcome ;-) 
But AFAIK there is a new router work in progress.

**Comment by franklinyu** [comment]
Oops, my bad. By "new router" did you mean dart-lang/angular2#202?

**Comment by zoechi** [comment]
exactly

**Comment by franklinyu** [comment]
Cool. Closing this and leaving comments there.
