### ISSUE TITLE
Misspelling templateUrl blocks application loading without any errors

### ISSUE THREAD

**Issue by tanelainla** [angular/angular.dart#1769]
When I mistype `templateUrl` in the `@Component` annotation and then import that component into my root component then the application stops loading and I don't get any error message into logs/debugger. Tracking down these kind of issues in larger applications is a pain (commenting stuff out etc.). There should be graceful error like "Templete not found" or something similar.

```
@Component(
    selector: 'item-list',
    templateUrl: 'mis_spelled_garbage_here',
```

**Comment by zoechi** [comment]
https://github.com/dart-lang/angular2 would be the correct GitHub repo
This repo is For Dart Angular 1

**Comment by tanelainla** [comment]
Yeah. Thanks. Noticed it already...
