### ISSUE TITLE
RouteParams.get() failed with 'int' is not a subtype of type 'String'

### ISSUE THREAD

**Issue by alescdb** [angular/angular.dart#1770]
Hi,

There seems to be a bug in `RouteParams`. 
`RouteParams.params` is defined as `Map<String, String>` but seems to be in fact a `Map<String, dynamic>`

If I wan't to navigate to my component via  `_router.navigate(['Carnet', {'page': 1}]);` and in my `CarnetComponent` I wan't to get the page argument with :

> int _page = int.parse(_routeParams.params['page']); // same with _routeParams.get('page')

I got an exception :

> EXCEPTION: type 'int' is not a subtype of type 'String' of 'source' where
> int is from dart:core
> String is from dart:core

My workaround for now is : 

> dynamic _page = _routeParams.params['page'];
> int page = _page;

--

PS : Also, since I'm talking about routes, I can't manage to have `hash (#)` in my routes, I've tried without success :

> provide(LocationStrategy, useClass: HashLocationStrategy)

So everytime I reload in dartium while developping I got a 404

**Comment by zoechi** [comment]
This repo is for Angular.dart 1.x
I guess you meant to report it in https://github.com/dart-lang/angular

The workaround should be to add quotes

```dart
_router.navigate(['Carnet', {'page': '1'}]);
```
These values are meant to be added  to the browsers URL bar and that only supports string

**Comment by zoechi** [comment]
There is also an active Gitter channel for Dart Angular discussions
https://gitter.im/dart-lang/angular

**Comment by alescdb** [comment]
Thanks @zoechi, I've submitted this issue to https://github.com/dart-lang/angular because in my opinion this is not a normal behaviour (storring an `int` inside a `String` should trigger an exception when assigned and not when accessed)
