### ISSUE TITLE
ng-repeat with a Map not working

### ISSUE THREAD

**Issue by saeimn** [angular/angular.dart#359]
When trying to use ng-repeat over a map:

&lt;span ng-repeat="(key, value) in {'a': 1, 'b': 2, 'c': 3}"&gt;
    {{key}}: {{value}}
&lt;/span&gt;

which is described in the Angular JS documentation:
http://docs.angularjs.org/api/ng.directive:ngRepeat#!

I get the following error:
type '_LinkedHashMap' is not a subtype of type 'List' of 'value'.

**Comment by ronyongxian** [comment]
does it support iterate map in ng-repeat now? for my opinion, just iterate with original order is ok. just like ng-options.
