### ISSUE TITLE
target="_self" doesn't work

### ISSUE THREAD

**Issue by magnayn** [angular/angular.dart#864]
As noted in (closed?!) issue: https://github.com/angular/angular.dart/issues/335

Setting target="_self" doesn't seem to work (I.E: make non-routed links fly).

It would be much better if the router had the ability to have the behaviour of "If no match for this link, treat as 'ordinary' link -- and to make this the /default/ behaviour.

As it stands, merely adding "<ng-view></ng-view>" into your page makes all other routes  suddenly stop working (IMO breaking the principle of 'least surprise').

Also, you may not have control over the HTML that is created for a component (it may not be angular), so having to specify target="_self" may not be a requirement that's easy to fulfill.

**Comment by amirul1000** [comment]
https://www.movie4k.to/

**Comment by amirul1000** [comment]
<iframe width="854" height="480" src="https://www.movie4k.to/" frameborder="0" ></iframe>

**Comment by amirul1000** [comment]
<iframe width="854" height="480" src="https://www.movie4k.to/" frameborder="0" ></iframe>
